<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>UnzipTool.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnzipTool.Core\UnzipTool.Core.csproj" />
    <None Include="..\..\deps\7z\7z.dll" Link="7z.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
